development:
  adapter: postgresql
  encoding: unicode
  database: corona
  pool: 2
  username: jamesmuriuki
  password: ''

production:
  adapter: postgresql
  encoding: unicode
  database: corona
  pool: 2
  username: ''
  password: ''